repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
    - id: check-yaml
      args:
        - --unsafe
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      exclude: src/back-end/images_to_video.py
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  exclude: src/back-end/images_to_video.py
  hooks:
    - id: seed-isort-config
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
  hooks:
    - id: isort
      exclude: src/back-end/images_to_video.py
