version: "3"

services:
  front-end:
    container_name: front-end
    image: thedockerman99/gallery-of-terror-dreams:front-end
    build:
      context: .
      dockerfile: ./src/front-end/Dockerfile
      args:
        - requirements=./pinned_requirements.txt
    volumes:
      - ./src/front-end:/app:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME:-stackdemo_local-network}
    environment:
      - DOCKER_CONTAINER=True

  back-end:
    container_name: back-end
    image: thedockerman99/gallery-of-terror-dreams:back-end
    build:
      context: .
      dockerfile: ./src/back-end/Dockerfile
      args:
        - requirements=./pinned_requirements.txt
    volumes:
      - ./src/back-end:/app/src/back-end  # Mounted as writable by default
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME:-stackdemo_local-network}
    environment:
      - DOCKER_CONTAINER=True

networks:
  stackdemo_local-network:
    driver: bridge
  stackdemo_deployment-network:
    driver: overlay
