version: "3"

services:
  front-end:
    container_name: front-end
    image: thedockerman99/gallery-of-terror-dreams:front-end
    build:
      context: .
      dockerfile: ./src/front-end/Dockerfile
      args:
        - requirements=./src/front-end/pinned_requirements.txt
    ports:
      - "8080:8080"
    restart: unless-stopped
    # volumes: ## for faster development
    #   - ./src/front-end:/app
    networks:
      - ${NETWORK_NAME:-stackdemo_local-network}
    environment:
      - CONTAINER_ORCHESTRATOR=True
    # command: streamlit run app.py --server.port 8080 --theme.base="dark" --browser.gatherUsageStats=false --logger.level="error"

  back-end:
    container_name: back-end
    image: thedockerman99/gallery-of-terror-dreams:back-end
    build:
      context: .
      dockerfile: ./src/back-end/Dockerfile
      args:
        - requirements=./src/back-end/pinned_requirements.txt
    ports:
      - "8000:8000"
    restart: unless-stopped
    # volumes: ## for faster development
    #   - ./src/back-end:/app
    networks:
      - ${NETWORK_NAME:-stackdemo_local-network}
    environment:
      - CONTAINER_ORCHESTRATOR=True
    # command: uvicorn creepy_story_generator:app --host 0.0.0.0 --port 8000 --reload

networks:
  stackdemo_local-network:
    driver: bridge
  stackdemo_deployment-network:
    driver: overlay
