version: "3"

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: ./src/front-end/Dockerfile
    volumes:
      - ./src/front-end:/code/src/front-end
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my-network
    environment:
      - DOCKER_CONTAINER=True
    command: streamlit run --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false /code/src/front-end/app.py

  back-end:
    container_name: back-end
    build:
      context: .
      dockerfile: ./src/back-end/Dockerfile
    volumes:
      - ./src/back-end:/code/src/back-end
    ports:
      - "8000:8000"
    restart: always
    networks:
      - my-network
    environment:
      - DOCKER_CONTAINER=True
    command: uvicorn creepy_story_generator:app --host 0.0.0.0 --port 8000 --reload

networks:
  my-network:
    driver: bridge
