version: "3"

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: ./src/front-end/Dockerfile
    volumes:
      - ./src/front-end:/code/src/front-end
    ports:
      - "8080:8080"
    environment:
      - MAIN_BG=/code/src/front-end/images/main_bg.jpg
    restart: always
    networks:
      - my-network
    command: streamlit run --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false /code/src/front-end/app.py

  back-end:
    container_name: back-end
    build:
      context: .
      dockerfile: ./src/back-end/Dockerfile
    volumes:
      - ./src/back-end:/code/src/back-end
    ports:
      - "8000:8000"
    environment:
      - IMAGE_DIR=/code/src/back-end/png_images/
      - AUDIO_FILE=/code/src/back-end/audio/audio.mp3
      - FLASH_VIDEO_FILE=/code/src/back-end/videos/flash_video.mp4
      - FINAL_VIDEO_FILE=/code/src/back-end/videos/final_video.mp4
    restart: always
    networks:
      - my-network
    command: uvicorn creepy_story_generator:app --host 0.0.0.0 --port 8000 --reload

networks:
  my-network:
