apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gallery-of-terror-dreams-tls
  namespace: default
spec:
  dnsNames:
    - gallery-of-terror-dreams.com
    - www.gallery-of-terror-dreams.com
  secretName: gallery-of-terror-dreams-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
