apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gallery-of-terror-dreams-ingress
spec:
  rules:
    - host: front-end.gallery-of-terror-dreams.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 8080
